// <auto-generated />
namespace RealEstateOffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agentidtest8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agentidtest8));
        
        string IMigrationMetadata.Id
        {
            get { return "202201081855160_agent-id-test-8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
